# Generated by Django 4.1 on 2024-07-25 05:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0003_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('zip_code', 'prefecture', 'address', 'user')},
        ),
    ]
